site_name: TEST Sensor Kits
site_url: https://sickag.github.io/TEST-Sensor-Kits
use_directory_urls: false
nav:
  - Home: index.md
  - TEST Sensor Kit: 
    - Overview: ./overview.md
    - Getting Started: ./getting-started.md
    - Code Snippets: ./produts.md
    - Tutorials: ./tutorials.md
    - FAQ: ./faq.md
  - Starter Kit 1:
    - Overview1: ./overview1.md
    - Technology1: ./technology1.md
    - Example1: ./example1.md
  - Starter Kit 2:
    - Overview2: ./overview2.md
    - Technology2: ./technology2.md
    - Example2: ./example2.md
  - Starter Kit 3:
    - Overview3: ./overview3.md
    - Technology3: ./technology3.md
    - Example3: example3.md

theme:
  name: readthedocs
  palette:
    primary: 'red'
    accent: 'green'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/SICK_logo_claim_top_right_blue_RGB.svg'
  features:
    - content.code.copy
copyright: "Â© SICK AG 2025"
extra:
  social:
plugins:
  - mkdocs-video

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true